CREATE TABLE cad_Usuario (
    id_Usuario int null AUTO_INCREMENT PRIMARY KEY,usuario_nome varchar(50),
    usuario_Supervisor INT
)

CREATE TABLE MOV_PROJETOS ( 
    id_PROJETOS int null AUTO_INCREMENT PRIMARY KEY, PROJETOS_nome varchar(50) 
    )

CREATE TABLE cad_Supervisor ( 
    id_Supervisor int null AUTO_INCREMENT PRIMARY KEY, Supervisor_nome varchar(70),
    id_Usuario int )


ALTER TABLE MOV_PROJETOS ADD COLUMN ID_USUARIO INT, ID_INSTRUMENTOS INT, ID_VEICULOS INT, ID_DEPARTAMENTO


ALTER TABLE CAD_SUPERVISOR
ADD CONSTRAINT FK_SUPERVISOR_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES CAD_USUARIO(ID_USUARIO)

ALTER TABLE CAD_VEICULOS
ADD CONSTRAINT FK_VEICULOS_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES CAD_USUARIO(ID_USUARIO)

ALTER TABLE CAD_USUARIO
ADD CONSTRAINT FK_USUARIO_DEPARTAMENTO FOREIGN KEY(ID_DEPARTAMENTO) REFERENCES CAD_DEPARTAMENTO(ID_DEPARTAMENTO)

ALTER TABLE MOV_PROJETOS
ADD CONSTRAINT FK_PROJETOS_INSTRUMENTOS FOREIGN KEY(ID_INSTRUMENTOS) REFERENCES CAD_INSTRUMENTOS(ID_INSTRUMENTOS)

ALTER TABLE MOV_PROJETOS
ADD COLUMN ID_USUARIO INT,
ADD COLUMN ID_INSTRUMENTOS INT,
ADD COLUMN ID_VEICULOS INT,
ADD COLUMN ID_DEPARTAMENTO INT;

INSERT INTO MOV_PROJETOS (PROJETOS_nome, ID_USUARIO, ID_INSTRUMENTOS, ID_VEICULOS, ID_DEPARTAMENTO) VALUES (APARTAMENTO, LAURO, APA, CORSA, PEDREIRO)

INSERT INTO CAD_USUARIO (usuario_nome)	(usuario_Supervisor) (ID_DEPARTAMENTO) VALUES  ('ANA'),('DUDA'), ('JULIO'), ('RICARDO'),('LAURO'), ('MAURO'), ('RH'), ('FINANCEIRO'), ('ADM') 
('ANA, RICARDO, RH'), ('DUDA, LAURO, FINANCEIRO'), ('JULIO, MAURO, ADM')

('ANA', 'RICARDO', 1),
  ('DUDA', 'LAURO', 2),
  ('JULIO', 'MAURO', 3);

  INSERT INTO MOV_PROJETOS (PROJETOS_nome, ID_USUARIO,	ID_INSTRUMENTOS, ID_VEICULOS, ID_DEPARTAMENTO) VALUES ('PARIS', 1,1,1,1), ('ROMA', 1,1,1,1), ('FRANÇA', 1,1,1,1), ('RJ', 1,1,1,1)
